version: '3.8'
services:
  backend:
    image: tuusuario/aula-central-backend:1.0
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb+srv://santimarimon66:Mongo123456@jacpolicarpa.kfl7ht6.mongodb.net/JACDB
      - JWT_SECRET=MiClaveSecretaSuperSeguraParaJWTDe256BitsOmas2026

  frontend:
    image: tuusuario/aula-central-frontend:1.0
    ports:
      - "80:80"
    depends_on:
      - backend