spring.application.name=system-pqrs

# Configuraci�n de Base de Datos SQL Server
spring.datasource.url=jdbc:sqlserver://EMUNA:1433;databaseName=proyecto;encrypt=false
spring.datasource.username=emuna
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuraci�n JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuraci�n del Servidor
server.port=8080
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt.secret=MiClaveSecretaSuperSeguraParaJWTDe256BitsOmas2026
jwt.expiration=86400000